2017-01-19 00:14:33,611[1] INFO  - 正在检测管理数据库是否存在...
2017-01-19 00:14:33,786[1] INFO  - 成功获取管理数据库！
******************************************** /n2017-01-19 00:14:38,929[14] INFO  - 正在检测管理数据库是否存在...
2017-01-19 00:14:38,995[14] INFO  - 成功获取管理数据库！
2017-01-19 09:44:51,468[1] INFO  - 正在检测管理数据库是否存在...
2017-01-19 09:44:55,181[1] INFO  - 成功获取管理数据库！
2017-01-19 10:05:23,489[1] INFO  - 正在检测管理数据库是否存在...
2017-01-19 10:05:27,517[1] INFO  - 成功获取管理数据库！
2017-01-19 10:07:51,054[1] INFO  - 正在检测管理数据库是否存在...
2017-01-19 10:07:54,240[1] INFO  - 成功获取管理数据库！
2017-01-19 10:09:13,290[1] INFO  - 正在检测管理数据库是否存在...
2017-01-19 10:09:16,349[1] INFO  - 成功获取管理数据库！
2017-01-19 10:11:58,861[1] INFO  - 正在检测管理数据库是否存在...
2017-01-19 10:12:02,476[1] INFO  - 成功获取管理数据库！
2017-01-19 10:30:01,270[1] INFO  - 正在检测管理数据库是否存在...
2017-01-19 10:30:04,197[1] INFO  - 成功获取管理数据库！
2017-01-19 10:43:41,328[1] INFO  - 正在检测管理数据库是否存在...
2017-01-19 10:43:44,385[1] INFO  - 成功获取管理数据库！
2017-01-19 10:43:56,850[5] ERROR - 删除子作品失败，请重试！
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 WallE.Data.MySql.DbAccessor.<>c__DisplayClass11_0.<SaveAsync>b__0() 位置 N:\Develop\WebDev\Server\WallE.Data.MySql\Implementations\_Accessor\DbAccessor.cs:行号 182
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 WallE.Data.MySql.DbAccessor.<SaveAsync>d__11.MoveNext() 位置 N:\Develop\WebDev\Server\WallE.Data.MySql\Implementations\_Accessor\DbAccessor.cs:行号 116
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 WallE.Data.MySql.DbAccessor.<DeleteAsync>d__15.MoveNext() 位置 N:\Develop\WebDev\Server\WallE.Data.MySql\Implementations\_Accessor\DbAccessor.cs:行号 224
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 WallE.Platform.Business.ProductionMgnt.<DeleteProductionDetailAsync>d__13.MoveNext() 位置 N:\Develop\WebDev\Server\WallE.Platform\Business\ProductionMgnt.cs:行号 410
2017-01-19 10:46:02,052[1] INFO  - 正在检测管理数据库是否存在...
2017-01-19 10:46:04,905[1] INFO  - 成功获取管理数据库！
2017-01-19 10:47:16,483[1] INFO  - 正在检测管理数据库是否存在...
2017-01-19 10:47:20,084[1] INFO  - 成功获取管理数据库！
2017-01-19 10:59:27,220[1] INFO  - 正在检测管理数据库是否存在...
2017-01-19 10:59:30,956[1] INFO  - 成功获取管理数据库！
